apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./devops/development/k8s/sql-server-deployment.yaml
            - ./devops/development/k8s/rabbitmq-deployment.yaml
            - ./devops/development/k8s/web-deployment.yaml
            - ./devops/development/k8s/worker-deployment.yaml
build:
    local:
        push: false
    artifacts:
        # - image: pacific/client
        #   context: client
        #   docker:
        #       dockerfile: Dockerfile
        #   sync:
        #       manual:
        #           - src: 'src/**/*.js'
        #             dest: .
        - image: bvaibhav95/pacific-web
          context: web
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: bvaibhav95/pacific-worker
          context: worker
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
