export enum JobStatus {
    READY = 'READY',
    RUNNING = 'RUNNING',
    PAUSED = 'PAUSED',
    STOPPED = 'STOPPED',
    KILLED = 'KILLED',
    RESUMED = 'RESUMED',
    CANCELLED = 'CANCELLED',
    SCHEDULED = 'SCHEDULED',
    SKIPPED = 'SKIPPED',
    PICKED = 'PICKED',
}
