export enum Events {
    Signup = 'user:signup',
    Login = 'user:login',
    Logout = 'user:logout',
    UserCreated = 'user:created',
    UserRead = 'user:read',
    UserUpdated = 'user:updated',
    UserDeleted = 'user:deleted',
    SourceCreated = 'source:created',
    SourceRead = 'source:read',
    SourceUpdated = 'source:updated',
    SourceDeleted = 'source:deleted',
    JobCreated = 'job:created',
    JobRead = 'job:read',
    JobUpdated = 'job:updated',
    JobDeleted = 'job:deleted',
    JobStarted = 'job:started',
    JobResumed = 'job:resumed',
    JobReady = 'job:ready',
    JobRunning = 'job:running',
    JobPaused = 'job:paused',
    JobStopped = 'job:stopped',
    JobPicked = 'job:picked',
    JobKilled = 'job:killed',
    JobScheduled = 'job:scheduled',
    JobCancelled = 'job:cancelled',
    JobSkipped = 'job:skipped',
}
